name: gps_attendance_system
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.6.5
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
