name: gps_attendance_system
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  calendar_timeline: ^1.1.3
  cloud_firestore: ^5.6.5
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#2A7F8E"
  image: "assets/icon/icon.png"
  color_dark: "#2A7F8E"
  image_dark: "assets/icon/icon.png"
  android: true
  ios: true
  android_12:
    image: "assets/icon/icon.png"
    icon_background_color: "#2A7F8E"
    image_dark: "assets/icon/icon.png"
    icon_background_color_dark: "#2A7F8E"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/
    - assets/images/avatars/
  generate: true
